export const categories = [
  {
    title: "Basic",
    image: "/src/assets/images/shopPage/categories/basic.jpg",
  },
  {
    title: "Skirts",
    image: "/src/assets/images/shopPage/categories/skirts.jpg",
  },
  {
    title: "Tops",
    image: "/src/assets/images/shopPage/categories/tops.jpg",
  },
  {
    title: "Home Wear",
    image: "/src/assets/images/shopPage/categories/homewear.jpg",
  },
  {
    title: "Jacket",
    image: "/src/assets/images/shopPage/categories/jacket.jpg",
  },
];

export const products = [
  {
    src: "/src/assets/images/shopPage/product.png",    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
  {
    src: "/src/assets/images/shopPage/product.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
    colors: ["#23A6F0", "#23856D", "#E77C40", "#23856D"],
  },
];
