export const products = [
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
  {
    src: "/src/assets/images/homepage/product-cover.png",
    title: "Graphic Design",
    description: "English Department",
    price: "$16.48",
    salePrice: "$6.48",
    address: "/",
  },
];
